# Generated by Django 4.2.1 on 2023-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("S", "SMALL"),
                            ("M", "MEDIUM"),
                            ("L", "LARGE"),
                            ("XL", "SUPER_LARGE"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "MALE"), ("Female", "FEMALE")], max_length=6
                    ),
                ),
                ("price", models.FloatField()),
                ("on_discount", models.BooleanField(default=False)),
                ("discount", models.PositiveIntegerField(default=17)),
                ("discount_start_date", models.DateTimeField(null=True)),
                ("discount_start_end", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["-on_discount", "name"],
            },
        ),
    ]
